name: 'JS Monorepo Deploy Nightly'
description: 'Deploys packages/* npm/vscode packages when the change'
author: 'Orta Therox'
inputs:
  since:              # change this
    description: 'The time between deploys'
    default: '1 day'
  cwd:              # change this
    description: 'The path to the folder which hosts packages'
    default: '.'
runs:
  using: 'node12'
  main: 'dist/index.js'
